In [1]:
import torch

### pytorch环境配置
参考文档：https://blog.csdn.net/weixin_47038938/article/details/115470086

机器的显卡驱动能支持的cuda版本太旧了，没办法用GPU，就用CPU凑合一下好了。。。

### pytorch是什么？
 - 作为Numpy的替代品，使用GPU的强大算力；
 - 提供最大的灵活性和高速的深度学习研究平台。
 
 Tensor（张量）
 
 与Numpy中的ndarrays类似，但pytorch中可以使用GPU
 
 Q：这里的张量和tensorflow与Numpy中的相似点与不同点是什么？
 A：

In [2]:
from __future__ import print_function
import torch

创建一个5*3矩阵，未初始化

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[-1.7047e-35,  8.3377e-43, -1.7046e-35],
        [ 8.3377e-43, -1.7045e-35,  8.3377e-43],
        [-1.7048e-35,  8.3377e-43, -1.7047e-35],
        [ 8.3377e-43, -1.7046e-35,  8.3377e-43],
        [-1.7050e-35,  8.3377e-43, -1.7046e-35]])


In [4]:
?torch.empty

创建一个随机初始化的矩阵

In [8]:
x = torch.rand(5, 3)
print(x)
# ----0填充
# x = torch.zeros(5, 3, dtype=torch.long)
# print(x)

tensor([[0.9933, 0.1812, 0.9859],
        [0.0469, 0.0324, 0.0916],
        [0.8373, 0.5855, 0.2555],
        [0.0856, 0.6218, 0.2838],
        [0.3040, 0.7790, 0.4401]])


张量运算 加法

In [9]:
y = torch.rand(5, 3)
print(x + y)
print(torch.add(x, y))

tensor([[1.7379, 1.1314, 1.6339],
        [0.1686, 0.9128, 0.1489],
        [1.4957, 1.0847, 0.7071],
        [0.7466, 1.5437, 1.0121],
        [0.6801, 1.0053, 0.7624]])
tensor([[1.7379, 1.1314, 1.6339],
        [0.1686, 0.9128, 0.1489],
        [1.4957, 1.0847, 0.7071],
        [0.7466, 1.5437, 1.0121],
        [0.6801, 1.0053, 0.7624]])


将运算结果输出到张量

In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.7379, 1.1314, 1.6339],
        [0.1686, 0.9128, 0.1489],
        [1.4957, 1.0847, 0.7071],
        [0.7466, 1.5437, 1.0121],
        [0.6801, 1.0053, 0.7624]])


替换

In [12]:
y.add_(x)
print(y)

tensor([[2.7313, 1.3127, 2.6197],
        [0.2155, 0.9452, 0.2406],
        [2.3330, 1.6702, 0.9627],
        [0.8322, 2.1655, 1.2959],
        [0.9841, 1.7843, 1.2025]])


**Note**

任何以"_"结尾的操作都会应结果替换原变量。

### Numpy转换
将Torch Tensor与Numpy数组相互转换很容易实现

两者贡献底层内存地址，修改一个会导致另一个的变化

将一个Torch Tensor转换为Numpy数组

In [14]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [15]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [16]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [17]:
print(b)

[2. 2. 2. 2. 2.]


Numpy转化为Torch Tensor

In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(b)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


所有的Tensor类型默认都是基于CPU，CharTensor类型不支持到Numpy的转换

In [21]:
torch.cuda.is_available()

C:\Users\admin\anaconda3\envs\pytorch\lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 6050). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:115.)
  return torch._C._cuda_getDeviceCount() > 0


False